import '../../app/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import TrpcProvider from '@/trpc/client/TrpcProvider'
import NextAuthSessionProvider from '@/nextauth/NextAuthSessionProvider'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 't3 stack starter',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  
  return (
    <html lang="en">
      <NextAuthSessionProvider>
        <TrpcProvider>
          <body className={`${inter.className} bg-slate-950 text-slate-50`}>{children}</body>
        </TrpcProvider>
      </NextAuthSessionProvider>
    </html>
  )
}
