import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import TrpcProvider from '@/trpc/client/TrpcProvider'
import NextAuthSessionProvider from '@/nextauth/NextAuthSessionProvider'
import NavBar from '@/components/NavBar'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 't3 stack starter',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  
  return (
    <html lang="en">
        <TrpcProvider>
         <NextAuthSessionProvider>
          <body className={`${inter.className} bg-slate-950 text-slate-50 h-screen`}>
            <NavBar />
            {children}
          </body>
         </NextAuthSessionProvider>
        </TrpcProvider>
    </html>
  )
}
