import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Provider from '@/trpc/client/Provider'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 't3 stack starter',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  
  return (
    <html lang="en">
      <Provider>
        <body className={`${inter.className} bg-slate-950 text-slate-50`}>{children}</body>
      </Provider>
    </html>
  )
}
